services:
    checkdomain.comodo.imap:
      class:  Checkdomain\Comodo\ImapWithSearch
      arguments: ['%checkdomain_comodo.imap.access%']

    checkdomain.comodo.imap_helper:
      class:  Checkdomain\Comodo\ImapHelper

    checkdomain.comodo.account:
      class:  Checkdomain\Comodo\Model\Account
      arguments: ['%checkdomain_comodo.account.user%', '%checkdomain_comodo.account.password%']

    checkdomain.comodo.communication_adapter:
      class: Checkdomain\Comodo\CommunicationAdapter
      arguments: [@checkdomain.comodo.account]

    checkdomain.comodo.util:
        class: Checkdomain\Comodo\Util
        arguments: [@checkdomain.comodo.communication_adapter, @checkdomain.comodo.imap, @checkdomain.comodo.imap_helper]